jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://amennet.postgres.database.azure.com:5432/amennetapi?user=postgres@amennet&password=khalilREZGUI2@&sslmode=require

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false